/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import git.GitRepo;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import model.Repo;
import model.RepoEntry;
import model.action.MakeGitSnapshot;

import org.eclipse.jgit.lib.ObjectId;
import org.eclipse.jgit.revwalk.RevCommit;
import org.eclipse.jgit.treewalk.TreeWalk;

/**
 *
 * @author U292156
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        try {
            Class.forName("org.sqlite.JDBC");
        } catch (ClassNotFoundException ex) {
            ctrlLogWin.append(ex.toString());
            ctrlLogWin.append("\n");
        }
        
    }

    public void Init() {
      ctrlRepository.removeAllItems();
      try {
        ResultSet rs = Repo.fetchAll();
        String wrkDir = new String();
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>)(ctrlRepository.getModel());
        while (rs.next()) {
          Repo adat = new Repo(rs);
          model.addElement(adat.getNeve());
          if (wrkDir.isEmpty()) {
             wrkDir = adat.getNeve();
          }
        }
      } catch (SQLException ex) {
        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ctrlSearchRepository = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ctrlIssueId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ctrlZipFilePrefix = new javax.swing.JTextField();
        ctrlSearchOutputDir = new javax.swing.JButton();
        ctrlStart = new javax.swing.JButton();
        ctrlOk = new javax.swing.JButton();
        ctrlRepository = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ctrlBranch = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        ctrlFullVersion = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        ctrlLogWin = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("res/Bundle"); // NOI18N
        setTitle(bundle.getString("MainTitle")); // NOI18N

        jLabel1.setText(bundle.getString("Repository")); // NOI18N

        ctrlSearchRepository.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/orange_folder_saved_search_22.png"))); // NOI18N
        ctrlSearchRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlSearchRepositoryActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("IssueId")); // NOI18N

        jLabel3.setText(bundle.getString("ZipBaseName")); // NOI18N

        ctrlZipFilePrefix.setToolTipText("");

        ctrlSearchOutputDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/orange_folder_saved_search_22.png"))); // NOI18N
        ctrlSearchOutputDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlSearchOutputDirActionPerformed(evt);
            }
        });

        ctrlStart.setText(bundle.getString("StartButton")); // NOI18N
        ctrlStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlStartActionPerformed(evt);
            }
        });

        ctrlOk.setText(bundle.getString("OkButton")); // NOI18N
        ctrlOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlOkActionPerformed(evt);
            }
        });

        ctrlRepository.setEditable(true);
        ctrlRepository.setModel(new DefaultComboBoxModel<String>());
        ctrlRepository.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlRepositoryActionPerformed(evt);
            }
        });

        jLabel4.setText(bundle.getString("lblBranch")); // NOI18N

        ctrlBranch.setModel(new DefaultComboBoxModel<String>());

        jLabel5.setText("Full version:");

        ctrlLogWin.setEditable(false);
        ctrlLogWin.setColumns(100);
        ctrlLogWin.setLineWrap(true);
        ctrlLogWin.setRows(5);
        ctrlLogWin.setWrapStyleWord(true);
        ctrlLogWin.setDoubleBuffered(true);
        jScrollPane2.setViewportView(ctrlLogWin);

        jMenu1.setText(bundle.getString("GitPackages.jMenu2.text")); // NOI18N

        jMenuAbout.setText(bundle.getString("AboutMenu")); // NOI18N
        jMenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAboutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ctrlStart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ctrlOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ctrlIssueId)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ctrlZipFilePrefix, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctrlRepository, 0, 240, Short.MAX_VALUE)
                                    .addComponent(ctrlBranch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctrlSearchRepository, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctrlSearchOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctrlFullVersion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(ctrlRepository, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ctrlSearchRepository, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ctrlBranch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctrlIssueId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ctrlZipFilePrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(ctrlSearchOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctrlFullVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctrlStart)
                    .addComponent(ctrlOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctrlSearchRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlSearchRepositoryActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select repository directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (ctrlRepository.getSelectedIndex() != -1) {
            chooser.setCurrentDirectory(new File((String)ctrlRepository.getSelectedItem()));
        }
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            ctrlRepository.addItem(chooser.getSelectedFile().getAbsolutePath());
            ctrlRepository.setSelectedIndex(ctrlRepository.getItemCount()-1);
        }
    }//GEN-LAST:event_ctrlSearchRepositoryActionPerformed

    private void ctrlSearchOutputDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlSearchOutputDirActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select target directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File currDir = new File(ctrlZipFilePrefix.getText());
        
        /// maybe its not a valid file, so we need to get the alid part.
        if (!currDir.exists()) {
          currDir = new File(currDir.getParent());
        }
        
        chooser.setCurrentDirectory(currDir);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            ctrlZipFilePrefix.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_ctrlSearchOutputDirActionPerformed

    private void ctrlStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlStartActionPerformed
        
        ctrlLogWin.setText("");
        MakeGitSnapshot mk = new MakeGitSnapshot(  ctrlRepository,
                                                   ctrlZipFilePrefix,
                                                   ctrlIssueId,
                                                   ctrlBranch,
                                                   ctrlFullVersion,
                                                   ctrlLogWin);
        mk.execute();
    }//GEN-LAST:event_ctrlStartActionPerformed

    private void ctrlOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlOkActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_ctrlOkActionPerformed

    private void ctrlRepositoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlRepositoryActionPerformed
      // TODO add your handling code here:
      try {
        String wrkDir = (String)ctrlRepository.getSelectedItem();
        ResultSet rs = Repo.fetchByNeve(wrkDir);
        String branch = new String();
        while (rs.next()) {
            Repo adat = new Repo(rs);
            ctrlIssueId.setText(adat.getIssueId());
            ctrlZipFilePrefix.setText(adat.getZipPrefix());
            branch = adat.getBranch();
        }
        DefaultComboBoxModel<String> cmodel = (DefaultComboBoxModel<String>)(ctrlBranch.getModel());
        cmodel.removeAllElements();
        GitRepo repo = new GitRepo(wrkDir);
        HashMap<ObjectId, String> branches = repo.getBranches();
        Iterator it = branches.values().iterator();
        while (it.hasNext()) {
          String br = (String)it.next();
          cmodel.addElement(br);
        }
        if (branch != null && !branch.isEmpty()) {
            cmodel.setSelectedItem(branch);
        }
        
      } catch (SQLException ex) {
        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
      } catch (IOException ex) {
        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_ctrlRepositoryActionPerformed

    private void jMenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAboutActionPerformed
        // TODO add your handling code here:
        AboutDialog dlg = new AboutDialog(this, true);
        dlg.setVisible(true);
    }//GEN-LAST:event_jMenuAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame frame = new MainFrame();
                frame.setVisible(true);
                frame.Init();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ctrlBranch;
    private javax.swing.JCheckBox ctrlFullVersion;
    private javax.swing.JTextField ctrlIssueId;
    private javax.swing.JTextArea ctrlLogWin;
    private javax.swing.JButton ctrlOk;
    private javax.swing.JComboBox ctrlRepository;
    private javax.swing.JButton ctrlSearchOutputDir;
    private javax.swing.JButton ctrlSearchRepository;
    private javax.swing.JButton ctrlStart;
    private javax.swing.JTextField ctrlZipFilePrefix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
